### ISSUE TITLE
getCurrentContextId() returns null when not sampling

### ISSUE THREAD

**Issue by naartjie** [googleapis/cloud-trace-nodejs#1025]
I am trying to use `LogEntry.trace` as a correlation identifier to tie different log messages together. I wasn't sure if this would be a good idea, but I got some confirmation from [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.trace_sampled):

> A non-sampled `trace` value is still useful as a request correlation identifier.

Being able to click on "Show matching entries" in the log view seems like a really useful thing to have:

<img width="448" alt="Screenshot 2019-05-13 at 20 33 18" src="https://user-images.githubusercontent.com/514563/57646097-16e83c80-75c0-11e9-8ace-a6cca64fb2f0.png">

The Bunyan logging wrapper uses the [`agent.getCurrentContextId()`](https://github.com/googleapis/nodejs-logging-bunyan/blob/d451b937139e5906ff66819788af6245256c08aa/src/index.ts#L44-L66). The problem is that `getCurrentContextId()` only seems to return a value if the current request is being sampled, and `null` otherwise.

Is this intended? Would it be possible to still return a traceId from `getCurrentContextId()` or perhaps expose another function to do this, for the sake of logging the trace id, to be able to correlate log entries.

**Comment by kjin** [comment]
I believe not having a context ID for unsampled requests is for performance reasons. We don't currently have an option give context IDs even for unsampled requests, but it's something I can look into implementing, especially given that our own documentation suggests it.

**Comment by naartjie** [comment]
Thanks for the super fast response @kjin 🚀 

If you think of any (even hacky) way to get the context ID in the meantime, please could you post it here also.

**Comment by kjin** [comment]
IIUC, the Bunyan logging wrapper's use of getCurrentContextId is internal, so if there would also have to be a way for you to override its value. I can't remember off the top of my head whether this is possible -- will take a look at the code in a bit.

**Comment by naartjie** [comment]
@kjin 

My project is using GKE/Cloud Run, and I'm just logging to stdout/stderr, so I'm not actually using the Bunyan library myself, hence I would be happy to use a workaround to extract the Context ID in my code.

Once a solution existed, do you think it would be a problem to take your suggested changes, and modify the internals of the (3?) Node.js GCP logging libraries to include `LogEntry.trace` in all log statements?

**Comment by kjin** [comment]
> My project is using GKE/Cloud Run, and I'm just logging to stdout/stderr, so I'm not actually using the Bunyan library myself, hence I would be happy to use a workaround to extract the Context ID in my code.

As a workaround maybe it's possible to use an existing correlation ID library when the `getCurrentContextId` doesn't return a useful value. There seems to be [some](https://www.npmjs.com/search?q=correlation) on npm but I'm not sure which are robust having not used them myself.

> Once a solution existed, do you think it would be a problem to take your suggested changes, and modify the internals of the (3?) Node.js GCP logging libraries to include `LogEntry.trace` in all log statements?

I think that makes sense.

**Comment by ofrobots** [comment]
@naartjie btw, you might want to check out the [express middleware](https://github.com/googleapis/nodejs-logging-bunyan#using-as-an-express-middleware) available through the logging-bunyan package. It provides a reliable way to correlate logs to context (the log function is on the request object), and ensures that a trace id is available even for non-sampled requests.

It would be good to know if that middleware works for your use-case and if not, it would be know to know the issues too.

**Comment by naartjie** [comment]
> As a workaround maybe it's possible to use an existing correlation ID library

@kjin thanks for the suggestion. I need to take a closer look, but I'm not sure if any would seamlessly pass the correlation ID with all incoming/outgoing HTTP requests. This is a very handy feature of `cloud-trace-nodejs`.

**Comment by naartjie** [comment]
> you might want to check out the express middleware

@ofrobots thanks, I did try to get it going, however:

1) I couldn't get it to work. I'm not sure what I did wrong. Should I log an issue?
2) I'm more interested about correlating log messages across service boundaries, rather than just for the current request.

**Comment by kjin** [comment]
Ok, I think I understand your use case better -- in that case a third-party correlation library would probably not be useful for you, what you would likely want indeed would be something like "regardless of sampling, assign a trace ID to each request (and propagate it)".

**Comment by naartjie** [comment]
@kjin yes, that is my use case, spot on. I couldn't have said it better.

**Comment by naartjie** [comment]
Hi @kjin, thank you for adding this. I am sorry it's taking me so long to verify the feature is working in my project, but I just haven't had time to work on it recently.

I'll be sure to feedback once I've started using this.

**Comment by kjin** [comment]
Thanks for the update, please let us know!
