### ISSUE TITLE
node-fetch requests do not get traced

### ISSUE THREAD

**Issue by kjin** [googleapis/cloud-trace-nodejs#1081]
As mentioned above, node-fetch requests are not traced, most likely because the module is already loaded when the Trace Agent starts, being one of its internal modules.

**Comment by mrdulin** [comment]
Sorry. I don't get it. I don't see a plugin for `node-fetch`. Why did you say:

> node-fetch requests are not traced

**Comment by kjin** [comment]
Yes, there is not (and should not be) a `node-fetch` plugin, as _any_ HTTP client library should work. This is due to Trace Agent internals.
