### ISSUE TITLE
[Q] How to create nested span?

### ISSUE THREAD

**Issue by mrdulin** [googleapis/cloud-trace-nodejs#1082]
**Is your feature request related to a problem? Please describe.**

```typescript
 app.get('/', async (req, res) => {
    try {
      const getDiscoveryChildSpan = tracer.createChildSpan({ name: 'getDiscovery' });
      const names = await DiscoveryService.getDiscovery(getDiscoveryChildSpan);
      getDiscoveryChildSpan.endSpan();
      res
        .status(200)
        .send(names)
        .end();
      return;
    } catch (err) {
      res.sendStatus(500);
    }
  });
```

I created a child span for `DiscoveryService.getDiscovery` operation and I pass this child span into this method. 

```typescript
public static async getDiscovery(span) {
    const operationAChildSpan = span.createChildSpan({ name: 'operationA' });
    await DiscoveryService.operationA();
    operationAChildSpan.endSpan();
    const operationBChildSpan = span.createChildSpan({ name: 'operationB' });
    await DiscoveryService.operationB();
    operationBChildSpan.endSpan();

    const httpChildSpan = span.createChildSpan({ name: 'rp.get' });
    const response = await rp.get(DiscoveryService.DISCOVERY_URL, { json: true });
    const names = response.items.map((item) => item.name);
    httpChildSpan.endSpan();
    return names;
  }
```

Within `DiscoveryService.getDiscovery` method, there are three operations, I try to create child span by calling `span.createChildSpan`. But it seems doesn't work. I check the `type.d.ts`, there is no `createChildSpan` method for child `span`. 

 **Describe alternatives you've considered**

And, I don't want to modify my codes aggressively like above.  I prefer using decorator and monkey patch like below:

```typescript
@trace()
  public static async operationA() {
    return new Promise((resolve) => setTimeout(resolve, 1000));
  }
```

 **Additional context**

Is there any better idea for creating custom trace and span for codes without modifying aggressively?

**Comment by kjin** [comment]
You can use `tracer.createChildSpan` for all of the spans. Our library doesn't make a distinction between children of root spans and children of child spans; the trace UI should automatically lay them out so that the `getDiscovery` inner spans appear under the outer `getDiscovery` span.

**Comment by mrdulin** [comment]
@kjin Thanks. Yes, this library doesn't distinct each span.

For example, there are three SQL queries to DB, but only show `pg-query` RPC for these three SQL queries. I can't distinct these SQL queries. For make a distinction for these SQL queries, maybe I should create my own custom child spans and name the spans with different names like: `findByUserId`, `findByAddressId`, `updateProfile`. After doing this, the trace UI will show these custom spans with DB query name and it's easy to distinguish.

**Comment by kjin** [comment]
That's a good idea, but what I meant (when I said "doesn't make a distinction between of children of root spans and children of child spans") is that there is no "explicit" nesting of children into other children. You can implicitly nest children by making sure the entirety of one span starts and ends within the interval of another, which it seems like that's what you're trying to do.

Let me know if you have any other concrete questions!
