### ISSUE TITLE
Initialize cloud trace within a function doesn't work.

### ISSUE THREAD

**Issue by mrdulin** [googleapis/cloud-trace-nodejs#1098]
**Is your feature request related to a problem? Please describe.**

For some reason, I need to initialize the cloud trace within an `async` function like this:

```js
const express = require('express');
const fetch = require('node-fetch');
const app = express();

async function getEnvVars() {
  return {
    keyFilename: '/Users/ldu020/workspace/github.com/mrdulin/nodejs-gcp/.gcp/stackdriver-trace-admin.json'
  };
}

async function asyncOperation() {
  return new Promise((resolve) => setTimeout(resolve, 1000));
}

let tracer;
app.get('/', async (req, res) => {
  console.count('Test cloud trace initialize within a function');
  tracer = require('@google-cloud/trace-agent').get();
  if (!tracer) {
    const envVars = await getEnvVars();
    tracer = require('@google-cloud/trace-agent').start({
      samplingRate: 0,
      bufferSize: 1,
      keyFilename: envVars.keyFilename
    });
  }

  tracer.runInRootSpan(
    {
      name: 'require-in-function'
    },
    async (rootSpan) => {
      await fetch('https://api.itbook.store/1.0/search/mongodb').then((res) => res.json());
      await asyncOperation();
      res.sendStatus(200);
      rootSpan.endSpan();
    }
  );
});

app.listen(8080, () => {
  console.info('server is listening on http://localhost:8080');
});
```

I can get the `tracer` object, the output of console.log is:

```bash
tracer: {"constants":{"TRACE_CONTEXT_GRPC_METADATA_NAME":"grpc-trace-bin","TRACE_CONTEXT_HEADER_NAME":"x-cloud-trace-context","TRACE_AGENT_REQUEST_HEADER":"x-cloud-trace-agent-request","TRACE_OPTIONS_TRACE_ENABLED":1,"TRACE_SERVICE_SPAN_NAME_LIMIT":127,"TRACE_SERVICE_LABEL_KEY_LIMIT":127,"TRACE_SERVICE_LABEL_VALUE_LIMIT":16383},"labels":{"HTTP_RESPONSE_CODE_LABEL_KEY":"/http/status_code","HTTP_URL_LABEL_KEY":"/http/url","HTTP_METHOD_LABEL_KEY":"/http/method","HTTP_RESPONSE_SIZE_LABEL_KEY":"/http/response/size","STACK_TRACE_DETAILS_KEY":"/stacktrace","ERROR_DETAILS_NAME":"/error/name","ERROR_DETAILS_MESSAGE":"/error/message","GAE_VERSION":"g.co/gae/app/version","GAE_MODULE_NAME":"g.co/gae/app/module","GAE_MODULE_VERSION":"g.co/gae/app/module_version","GCE_INSTANCE_ID":"g.co/gce/instanceid","GCE_HOSTNAME":"g.co/gce/hostname","HTTP_SOURCE_IP":"/http/source/ip","AGENT_DATA":"/agent"},"spanTypes":{"UNCORRELATED":"UNCORRELATED","DISABLED":"DISABLED","UNSAMPLED":"UNSAMPLED","ROOT":"ROOT","CHILD":"CHILD"},"traceContextUtils":{},"propagation":{},"enabled":false,"logger":null,"config":null,"policy":{"sampler":{},"urlFilter":{},"methodsFilter":{},"contextHeaderFilter":{"contextHeaderBehavior":"default"}},"headerPropagation":null,"pluginNameToLog":"no-plugin-name"}
```

But I can't get trace and rootSpan at GCP console trace list.

 **Describe the solution you'd like**

So, is there any solution for this case without changing the way I fetch my application environment variables. 

It seems like the question can be called "How to initialize the cloud trace asynchronously?" as well.

 **Describe alternatives you've considered**

I am not sure there is an API can handle this case.

**Comment by kjin** [comment]
Maybe this won't work for the first request, but I would at least expect this to work for subsequent requests, because the Trace Agent at that point would already be initialized. Could you verify whether this is the case?

Also, is the `require-in-function` root span simplified, or is it the code that is actually running? Because as is, one problem is that it seems to be started/ended almost instantaneously, and the Cloud Console UI won't show traces that are 0ms long.

**Comment by mrdulin** [comment]
@kjin Affirmative. I added some operations in the controller to make sure the duration over 0 ms long. 

Here is my test result:

```bash
curl http://localhost:8080
```
I access the `/` route 5 times. 

```bash
Test cloud trace initialize within a function: 1
Test cloud trace initialize within a function: 2
Test cloud trace initialize within a function: 3
Test cloud trace initialize within a function: 4
Test cloud trace initialize within a function: 5
```

There is no trace and span in cloud console UI.

![图片](https://user-images.githubusercontent.com/17866683/62913386-6bb57200-bdbe-11e9-9280-39e43265db70.png)

**Comment by kjin** [comment]
Let me try to repro this and get back to you!

**Comment by kjin** [comment]
After running it, it seems like this could be a problem:

```js
  tracer = require('@google-cloud/trace-agent').get();
  if (!tracer) {
    // ...
  }
```

This should be something more like:

```js
  tracer = require('@google-cloud/trace-agent').get();
  if (!tracer.enabled()) {
    // ...
  }
```

But `enabled` is a private property. I think I can add this to the public API given the simplicity of the change. In the meantime:

```js
function isTracerEnabled() {
  try {
    const config = tracer.getConfig();
    return config.enabled;
  } catch (e) {
    return false;
  }
}

// In the request handler
{
  tracer = require('@google-cloud/trace-agent').get();
  if (!isTracerEnabled()) {
    // ...
  }
}
```

**Comment by mrdulin** [comment]
@kjin Great. It works, thanks.  Hope you can improve the documentation about this case. Maybe make some explanations for how `isActive` and `config.enabled` works.

![图片](https://user-images.githubusercontent.com/17866683/62991613-c31d1600-be82-11e9-866a-ac0acedfe154.png)

Is there anything I should take care when I use cloud trace like the way you provide?

**Comment by kjin** [comment]
Great!

> Hope you can improve the documentation about this case. Maybe make some explanations for how `isActive` and `config.enabled` works.

The README [currently states](https://github.com/googleapis/cloud-trace-nodejs/tree/d14d4478391217c3beb733bfd3bcef5dbb5385bb#accessing-the-api) that the return value of both `get` and `start` is an object of type `Tracer`.

> Is there anything extra I should take care when I use cloud trace like the way you provide?

Actually, now that I see the code again, may I suggest an alternative approach:

```js
let tracer;
{
  if (!tracer) {
    tracer = require('@google-cloud/trace-agent').start({/*...*/});
  }
  // ...
}
```

In other words, simply don't use `get`, because `tracer` only needs to be assigned once. This obviates the need for `isActive` overall.
