### ISSUE TITLE
Cloud Run metadata lag

### ISSUE THREAD

**Issue by gotwalt** [googleapis/cloud-trace-nodejs#1114]
In doing some testing with Cloud Trace agent running on Google Cloud run, we're running in to unexplained lag as the result of repeated slow requests to `http://metadata.google.internal./computeMetadata/v1/instance/service-accounts/?recursive=true`. These requests typically take ~5s and appear randomly across requests as far as we can tell.

<img width="533" alt="Screen Shot 2019-09-10 at 5 12 52 PM" src="https://user-images.githubusercontent.com/225575/64659000-74658c00-d3ee-11e9-8fe6-35ce917cd3c7.png">

The call stack for those metadata calls:
```
requestTrace (/opt/xxx/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-http.js:96:26)
<anonymous function> (/opt/xxx/node_modules/node-fetch/lib/index.js:1432:15)
Promise
fetch (/opt/xxx/node_modules/node-fetch/lib/index.js:1401:9)
<anonymous function> (/opt/xxx/node_modules/@google-cloud/storage/node_modules/gaxios/src/gaxios.ts:70:27)
next [as next]
<anonymous function> (/opt/xxx/node_modules/@google-cloud/storage/node_modules/gaxios/build/src/gaxios.js:19:71)
Promise
__awaiter (/opt/xxx/node_modules/@google-cloud/storage/node_modules/gaxios/build/src/gaxios.js:15:12)
request [as request] (/opt/xxx/node_modules/@google-cloud/storage/node_modules/gaxios/build/src/gaxios.js:60:16)
```

Environment Details
* Node 10 Alpine image
* `@google-cloud/trace-agent` version 4.0.1

I can work on a minimal repro case, but it seems to be a function of request sampling and dynamic node instantiation, so it's hard to get a good look at whatever is causing this. Is there something I'm obviously doing wrong?

**Comment by gotwalt** [comment]
For whatever it's worth, I just set up a simple express endpoint that uses node-fetch to request that endpoint. Non-statistically-defensible sampling from the same instance says it averages 1-2ms.

**Comment by JustinBeckwith** [comment]
Greetings @gotwalt!  This is a known bug, and @bcoe is actively working on a fix.  Apologies for the trouble!

**Comment by kjin** [comment]
@JustinBeckwith Is there a link to this known bug?

**Comment by gotwalt** [comment]
Can confirm that @stephenplusplus's [recco in this thread](https://github.com/googleapis/nodejs-datastore/issues/481#issuecomment-530484597) to switch from alpine to slim appears to work around the issue.

**Comment by bcoe** [comment]
@gotwalt closing, as there's both a workaround and the underlying cause should also be addressed :+1:
