### ISSUE TITLE
Feature Request: extend plugin to add labels to each span

### ISSUE THREAD

**Issue by davidbielik** [googleapis/cloud-trace-nodejs#1139]
**Is your feature request related to a problem? Please describe.**

I'm using `trace-agent` within an Express.js application and it works wonderfully with one line of code and zero effort 😎. 

I would like to add a custom label to every trace, though, and since I am not creating the traces myself, I don't have any interface to do so. 

This ability would allow me to add additional data for filtering/searching within Stackdriver (for example, filtering by customer tier, feature, a/b test variant, etc.

 **Describe the solution you'd like**

It would be great if I could somehow initialize with an additional (new) parameter of labels to be appended to each trace, like so:

```
require('@google-cloud/trace-agent').start({
    samplingRate: 0,
    ignoreMethods: ['options'],
    labels: {custom1: 'value1', custom2: 'value2'} // new 
});
```

 **Describe alternatives you've considered**

I've looked into how the [express plugin](https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/plugins/plugin-express.ts) works today, but can't seem to find a way to extend it manually.

Thanks!

**Comment by kjin** [comment]
Hi @davidbielik, thanks for the suggestion! Would it serve your use case to have an Express middleware that would add a label to each trace like this: https://gist.github.com/kjin/61bdac2f5cd1c6ef1a13efb2765a69a4

**Comment by davidbielik** [comment]
Hi @kjin - thanks for that - will work perfectly!

**Comment by davidbielik** [comment]
Hi @kjin I have a similar question - how would I disable the tracer from running in a certain route within Express?

I have a few routes that do hundreds of async requests and I don't want to trace these routes. I don't see any methods in the docs on how to temporarily disable a tracer.

https://googleapis.dev/nodejs/trace/latest/miscellaneous/functions.html

**Comment by kjin** [comment]
You can use `ignoreUrls` to prevent certain routes from being traced. Does that work for you?
