### ISSUE TITLE
Support for Fastify

### ISSUE THREAD

**Issue by PatrickHeneise** [googleapis/cloud-trace-nodejs#1167]
**Is your feature request related to a problem? Please describe.**

I installed the trace agent in our API via npm and added it to the first line when initialising the API with fastify.io.

 **Describe the solution you'd like**

Fastify has a similar routing system as Express, so I was hoping this would work out of the box. But after deploying the API on Google Cloud Run, I didn't get any results in the console.

 **Additional context**

I have no idea where to start / look for this. Any hint for a plugin / extension would be helpful to get this up and running.

**Comment by kjin** [comment]
Hi @PatrickHeneise, we aren't adding support for tracing additional libraries at this time, as we are planning to converge with [OpenCensus for Node.js](https://github.com/census-instrumentation/opencensus-node) (also see #977). Sorry about that!

**Comment by PatrickHeneise** [comment]
That sounds like a good plan. Is there a timeline?

**Comment by Mistic92** [comment]
Hi, is there update for this task? I'm using nestjs with fastify.

**Comment by kintel** [comment]
New features will go into [OpenTelemetry](http://opentelemetry.io), which is the successor to OpenCensus. Please open an feature request against https://github.com/open-telemetry/opentelemetry-js-contrib.
