### ISSUE TITLE
Logging an object using addLabel in a Node 10 Google Cloud Function creates a line per property

### ISSUE THREAD

**Issue by jpreynat** [googleapis/cloud-trace-nodejs#1178]
#### Environment details

  - OS: Google Cloud Function
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `@google-cloud/trace-agent` version: 4.2.0

#### Steps to reproduce

Creating a child span and adding a label using the `span.addLabel()` method creates a logging line per object property, instead of `JSON.stringify`ing the object on one line.

This is very annoying for two reasons:
- It loses context in search (object properties are no more searchable together in StackDriver)
- It increases the number of logs a lot, which leads us to quota errors

This didn't happen in Node 8 Cloud Functions, so I'm wondering if this is directly linked to this module or if this is the Node 10 environment that leads to this behavior.

**Comment by kintel** [comment]
@jpreynat Sorry for late response: Could you clarify what you mean by "creates a logging line"? Are you referring to manually created logs sent to Google Cloud Logging?

A screenshot or minimal code example would help us tremendously in identifying the problem.

**Comment by jpreynat** [comment]
Hi @kintel,

No worries, my message wasn't very clear at the time, and I realized afterwards that my problem relied on the NodeJS execution environment for Google Cloud Functions, not in this module.
We have an abstraction in our code that uses `@google-cloud/trace-agent` and capture labels during execution and `console.log` all of them at the end for debugging purposes.
I foolishly believed that `@google-cloud/trace-agent` was also responsible for the logging part, but of course that's not the case.

Here's the detail of the behavior that I encountered if this can be of interest for someone, but feel free to close the issue.

Just to recap, if you have an object like:

```ts
const obj = {
  name: 'john',
  age: 30
};
```

and do a `console.log(obj);` in the NodeJS 8 runtime for GCF, you end with something like:

```
2020-05-29T14:52:01.160Z <fn-name> <execution-id> { name: 'john', age: 30 }
```

whereas in NodeJS 10 runtime, you end with:

```
2020-05-29T14:52:01.160Z <fn-name> <execution-id> { name: 'john',
2020-05-29T14:52:01.160Z <fn-name> <execution-id> age: 30 }
```

We ended up `JSON.stringify`ing our labels and it now properly renders them in one line in the logging console.

**Comment by kintel** [comment]
Thanks for the clarification and good that you got it sorted - I'll close this.
FYI:
* Google Cloud Functions went through a rather large change from node8 to node10 -> the node10 runtime is not fully Open Source.
* If you use Google's logging APIs, you should be able to correlate traces with logs, and benefit from such correlation by having both tracing and logging UIs in Google Cloud Console create links to each other (see e.g. LogEntry.trace: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry).
