### ISSUE TITLE
Support hapi@19

### ISSUE THREAD

**Issue by SantiMA10** [googleapis/cloud-trace-nodejs#1193]
#### Environment details

  - OS: Google App Engine
  - Node.js version: 12.14.1
  - npm version: 6.13.4
  - `@google-cloud/trace-agent` version: ^4.2.5

#### Steps to reproduce

  1. Create a new project with hapi@19
  2. Add @google-cloud/trace-agent
  3. Deploy it to Google App Engine
  4. No trace information is shown at Stackdriver Trace Console 😞

**Comment by AdriVanHoudt** [comment]
This works for us with hapi 19, trace agent 4.2.5, node 12.16 (I'm fairly sure 12.14 did as well) on compute engine with no special config.
Did you call .start()?

**Comment by SantiMA10** [comment]
It's working now, maybe there was some lag ingesting the traces.

**Comment by SantiMA10** [comment]
@AdriVanHoudt can I open a PR to update the supported hapi versions in the README?
