### ISSUE TITLE
unsure if "memory leak" message refers to the client or to the host app

### ISSUE THREAD

**Issue by eli-darkly** [googleapis/cloud-trace-nodejs#1231]
Hi. I haven't used Cloud Trace myself, but I'm trying to track down an issue that a user of my SAAS product is having where they are getting the following message from Cloud Trace:

`@google-cloud/trace-agent ERROR TraceApi#createChildSpan: [http@12.14.1:https] Adding child span [stream.launchdarkly.com] will cause the trace with root span [/v1/events] to contain more than 200 spans. This is likely a memory leak.`

The hostname stream.launchdarkly.com is a service endpoint in my product - it's expected that they would be making requests to it. What we're not sure about is whether this message is saying that _my_ service client code is leaking, or that Cloud Trace thinks its own data structures may be leaking. Based on the references to "spans", and the reference to "context confusion" in the [code comments](https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/trace-api.ts), and [this earlier issue](https://github.com/googleapis/cloud-trace-nodejs/issues/838) as well as [this](https://github.com/googleapis/cloud-trace-nodejs/issues/632), I suspect it might be the latter.

The documentation doesn't say anything about this kind of thing as far as I can tell, and the tool doesn't seem to be intended to diagnose memory issues in the host application (I can't see how it _could_ do so, either - how could it know whether the cause of a leak in the host app was context confusion or something else?).

**Comment by kjin** [comment]
If you do any kind of request pooling or otherwise reuse objects between different requests in your client library then it could be as a result of that. Keep in mind this could be as a result of dependencies like Bluebird if you use it. But if your service's client code is relatively thin it might be an issue with your user's codebase or their dependencies. You're right that we can't really tell from the point of view of our agent, so I can't say for certain much else than that.

**Comment by eli-darkly** [comment]
@kjin Could you say more about what you mean by "otherwise reuse objects between different requests"? It's hard for me to imagine a scenario where handling different requests would _not_ involve referencing some of the same objects.

Also, am I wrong that this specific message was added because the client was previously known to have had a leak? The message and the code comments seem to me like they're mainly geared toward internal development of the library - it's unclear to me whether the concept of a root span containing more than 200 child spans is something users of this tool are expected to understand, and there doesn't seem to be anything in the documentation about this error.

**Comment by kjin** [comment]
> @kjin Could you say more about what you mean by "otherwise reuse objects between different requests"? It's hard for me to imagine a scenario where handling different requests would _not_ involve referencing some of the same objects.

My bad, I should have been clearer - I'm referring to retaining request data that could conceivably be used in or linked to a different request. A common case of this would be userspace request pooling, where maybe you have a specific number of connections available at a time. If you have a pool of 16 reusable connections, say, it's possible that the 17th request accidentally gets associated with the 1st by our Trace Agent. Batching requests could be another example. Another might be awaiting a Promise that was constructed globally or in a different handled request than the current one.

> Also, am I wrong that this specific message was added because the client was previously known to have had a leak? The message and the code comments seem to me like they're mainly geared toward internal development of the library - it's unclear to me whether the concept of a root span containing more than 200 child spans is something users of this tool are expected to understand, and there doesn't seem to be anything in the documentation about this error.

We do describe the distinction between root and child spans in our README, with the relationship being that child spans generally correspond to outgoing RPCs made on behalf of a root span which corresponds to an incoming request (all of this is referring to the user's server). The error message is saying we _think_ that more than 200 outgoing RPCs are being associated with a single incoming request, and that this is not normal. If it's known to be normal (by the app developer) of course this limit can be raised, but 200 is the default.

I think our original intention of the message was to help us debug issues when the user posted their error log, although I don't think it's too esoteric for our users to use this information as well.

**Comment by eli-darkly** [comment]
Thanks, that's helpful and gives me more of an idea what to look at in the code. Probably the best way for me to proceed is to just use regular memory profiling tools while exercising these code paths heavily.
