### ISSUE TITLE
express plugin will always call async handlers

### ISSUE THREAD

**Issue by hjr3** [googleapis/cloud-trace-nodejs#1235]
The use of something like https://github.com/Abazhenov/express-async-handler with the express plugin causes some very strange behavior. The async handler is always ran, even if earlier middlware sends back a response. I also believe the async handler is ran outside of the context of the request, so if there is any rejected promise or exception will trigger the `process.on('uncaughtException')` and `process.on('unhandledRejection')` handlers.

#### Environment details

  - OS: (whatever GAE standard uses)
  - Node.js version: 12
  - npm version: 6.13.4
  - `@google-cloud/trace-agent` version: 4.2.2

#### Steps to reproduce

Given the following code:

```ts
import * as gcpTrace from '@google-cloud/trace-agent';
import express from 'express';
import asyncHandler from 'express-async-handler';

process.on('unhandledRejection', e => {
  console.error('Unhandled Rejection', e);
  process.exit(1);
});

gcpTrace.start();

const app = express();

app.get(
   '/',
   (req, res, next) => {
      res.status(200).send('I should prevent the next handler from being called');
   },
   asyncHandler(async (req, res, next) => {
      Promise.reject(new Error('I should never be called'));
   }),
);
```

The async handler will be always called, even though the first handler returns a 200. I made the async handler reject to show that, despite the `asyncHandler` using [.catch](https://github.com/Abazhenov/express-async-handler/blob/master/index.js#L5), the `process.on('unhandledRejection')` will be called and cause the process to exit.

**Comment by kjin** [comment]
Sorry, I can't seem to reproduce this with the code you supplied. Since you gave TS I thought transpilation target might affect behavior -- I tried es5 and also no downleveling and didn't observe the rejected Promise. Do you have more info on when you observe this?

**Comment by hjr3** [comment]
@kjin thank you for taking a look. I checked and the above does not reproduce it for me either. Let me spend some time creating a reproducible case in a repo that I can share with you.
