### ISSUE TITLE
app sample broken: TypeError: The `GET` method cannot be used with a body

### ISSUE THREAD

**Issue by kintel** [googleapis/cloud-trace-nodejs#1246]
#### Environment details

  - OS: macOS
  - Node.js version: 10.20.1
  - npm version:   6.14.4
  - `@google-cloud/trace-agent` version: 4.2.5

#### Steps to reproduce

```
cd samples
npm install
npm start
curl localhost:8080
```

```
-> "TypeError: The `GET` method cannot be used with a body"
```

#### Notes

It looks like this example is using the `got` API wrongly: The `json` argument is supposed to be a serializable POJO, not a boolean: https://github.com/sindresorhus/got#json

**Comment by kintel** [comment]
Idea: We should have an automated test of this example, as this is used as the official Node.js example for the Cloud Trace product

**Comment by bcoe** [comment]
> We should have an automated test of this example, as this is used as the official Node.js

I agree, this would be smart 👍 we already run `sample-tests` as part of CI/CD.
