### ISSUE TITLE
Improve test of sample app

### ISSUE THREAD

**Issue by kintel** [googleapis/cloud-trace-nodejs#1259]
The sample app test (https://github.com/googleapis/cloud-trace-nodejs/blob/master/samples/test/test.js) really just checks that the sample app process starts, not that it does the right thing.
This caused #1246 to go undetected for an unknown amount of time. Since this is also the official example used for the Cloud Trace public documentation, it important that it works at all times.

**Comment by punya** [comment]
We are prioritizing OTel integration over this proprietary agent, so we probably won't improve the sample.
