### ISSUE TITLE
Support pg v8

### ISSUE THREAD

**Issue by seeARMS** [googleapis/cloud-trace-nodejs#1272]
Trace doesn't work with the newest pg major release (v8). It would be great to add support for this, as currently the lib only works with versions 6-7.

**Comment by rueian** [comment]
It seems that the current logic of pg plugin can be used with v8 directly.

**Comment by kintel** [comment]
TODO:
* [ ] Add v8 support
* [ ] Make sure v8 is tested
* [ ] Evaluate how well pg in general and pg v8 is supported in OpenTelemetry, and open tickets where appropriate

**Comment by danvk** [comment]
Here's a hack to enable the v7 pg plugin on pg v8. Use at your own peril.

```ts
for (const patch of require('@google-cloud/trace-agent/build/src/plugins/plugin-pg')) {
  if (patch.versions === '^7.x') {
    patch.versions = '^7.x || ^8.x';
  }
}
```

**Comment by weyert** [comment]
How can we progress this pull request?

**Comment by contra** [comment]
Looking at the actual changelog the only reason it went from v7 to v8 is because node 6 support was dropped: https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg800

It should be really quick to just add 8.x to the versions list.

**Comment by bcoe** [comment]
@contra thanks for taking a look, I'll bring this issue up internally as well, see if I can get anyone's 👀 on it.

**Comment by Zorato** [comment]
Hey @bcoe any good news on this?

**Comment by bcoe** [comment]
@Zorato unfortunately no updates, @kintel do you know who a good person to loop in would be?

**Comment by kintel** [comment]
@jarek-dudek @gkf Could you follow up on this?

**Comment by gkf** [comment]
Sorry I don't have much to add. This is effectively on our backlog currently.

**Comment by punya** [comment]
We don't expect to be able to add pg v8 support to the Cloud Trace NodeJS agent any time soon.

Please consider using OpenTelemetry instead -- [@opentelemetry/instrumentation-pg](https://www.npmjs.com/package/@opentelemetry/instrumentation-pg) supports pg v8.x.

**Comment by yasha-spare** [comment]
@punya does this mean `cloud-trace-nodejs` is essentially abandoned, and people should generally be switching to a different approach, like OpenTelemetry, for sending traces to GCP tracing?

**Comment by punya** [comment]
Hi @yasha-spare, thanks for the question - it's a reasonable one.

Cloud-trace-nodejs will continue to fix bugs and add security patches. We will consider merging new feature contributions (depending on the anticipated maintenance cost). But we won't develop new features ourselves.

To your larger question: yes, we recommend that new codebases start out with OTel. Existing users of cloud-trace-nodejs need to make a more nuanced decision about when their library dependencies will no longer be supported by cloud-trace-nodejs.

We intend to add documentation (a migration guide) to help with this process.

**Comment by yasha-spare** [comment]
Cool, thanks for the swift reply/clarification @punya !
