### ISSUE TITLE
[Question] Does cloud-trace-nodejs support head based sampling?

### ISSUE THREAD

**Issue by jyparketc** [googleapis/cloud-trace-nodejs#1273]
**Is your feature request related to a problem? Please describe.**

Does cloud-trace-nodejs support[ head based sampling](https://www.jaegertracing.io/docs/1.18/sampling/)?

I've run micro-services that send **high-rate request**.

A  -------- context propagation ----------> B

And I found that sometimes span A is sampled but span B is unsampled in same trace.

That is because [this.sampler.shouldTrace(options.timestamp)](https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/tracing-policy.ts#L191) returns false for span B.

I'm not sure but I think sampling rate is depended on each trace-agent. It is not considered trace context.

I wondering that it is normal operations?

 **Describe the solution you'd like**
 supports head based sampling?

**Comment by kintel** [comment]
Yes, we do head-based sampling, but we may re-sample to respect the configured sampling rate.
I believe a pure head-based sampling can be set up with a config like this:
```
require('@google-cloud/trace-agent').start({
  samplingRate: 0,
  contextHeaderBehavior: 'required',
});
```

Note: This will probably not create any root spans, but require all requests to come with a propagation header.

Let me know how this works for you.

**Comment by jyparketc** [comment]
@kintel , it works well to me!
thank you for your help :+1:
