### ISSUE TITLE
plugin-restify.js not upgraded to 8.x

### ISSUE THREAD

**Issue by Valrathius** [googleapis/cloud-trace-nodejs#1275]
Hi,

I have tried to get the trace-agent running using restify but it is not working. My question is could it be related to the plugin-restify.js not being properly updated.

I have the same problem locally as with the App Engine Standard environment.

(I don't know if this issue should be filed here or at another place so forgive me if this is the wrong area.)

#### Environment details

  - OS: Mac OS X 10.15.5
  - Node.js version: v12.16.1
  - npm version: 6.13.4
  - `@google-cloud/trace-agent` version: 4.2.5

#### Steps to reproduce

1. `npm install @google-cloud/trace-agent`
2. Browse to ./node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-restify.js
3. line 16 still says: `const SUPPORTED_VERSIONS = '<=7.x';`

**Comment by kintel** [comment]
This was fixed by #1250 and will be released in version 5.0.0 (#1241) which is expected to land soon.
