### ISSUE TITLE
Probably a good idea to share the require-in-the-middle types with DefinitelyTyped :)

### ISSUE THREAD

**Issue by jcao219** [googleapis/cloud-trace-nodejs#1288]
Hi @kjin hi all,

It would be great to contribute to definitelytyped for the require-in-the-middle types

**Comment by michaelsafyan** [comment]
To help in triaging this, can you provide a little more context regarding this request? What is the advantage of putting the TypeScript type definitions in [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped) vs keeping them local to this repository?

**Comment by punya** [comment]
Closing as stale.
