### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by richardscarrott** [googleapis/cloud-trace-nodejs#1303]
GraphQL has just a single endpoint which means the http method and path aren't particularly interesting:

<img width="565" alt="Screenshot 2020-08-25 at 18 53 56" src="https://user-images.githubusercontent.com/539309/91210032-87a75f80-e704-11ea-8ac1-930242bc1dcc.png">

I'm not 100% sure how you're instrumenting http / express but I wonder if it would be possible to read the [gql operation](https://graphql.org/learn/queries/#operation-name) name from the request body (expensive?) and use that instead?

Perhaps the API allows consumers to add metadata to the out-the-box spans so when our GraphQL router handles a request it could perhaps add the operation name itself?

**Comment by kintel** [comment]
We're not planning to add new functionality to this library; all new development happens in [OpenTelemetry](https://open-telemetry.github.io/opentelemetry-js/).

I'm not familiar with how well OpenTelemetry supports GraphQL, but if your run into any issues, I would suggest opening an issue against https://github.com/open-telemetry/opentelemetry-js-contrib, asking for (better) GraphQL integration.
There's also a [public OpenTelemetry Node.js Gitter chat](https://gitter.im/open-telemetry/opentelemetry-node) with a lot of developers and users who may be able to help.

For this library, I think the best workaround for now would be to manually instrument GraphQL calls in your user-space code and add span labels with appropriate metadata there.

**Comment by richardscarrott** [comment]
@kintel interesting, is there any documentation re: using opentelementry-js with GCP / GKE?

I was looking through this library's API and found `tracer.getCurrentRootSpan()` but not sure if the following would be safe:

```js
const tracer = require('@google-cloud/trace-agent').start();
const express = require('express');

const app = express();

app.use(async (req, res, next) => {
   try {
      await sleep(1000);
      next();
   } catch(ex) {
      next(ex);
   } 
});

app.post('/graphql', (req, res, next) => {
   const rootSpan = tracer.getCurrentRootSpan(); // If 10 requests arrived all at once, which span would this return?...is this an async_hooks trick?
   const operationName = getOperationName(req);
   rootSpan.addLabel('operationName', operationName)
   rootSpan.addLabel('/http/url', `/graphql (${operationName})`)
   // ...handle gql request
});
```

1) How does `tracer.getCurrentRootSpan()` know which span belongs to this request, is it some async_hooks magic?
2) Is it possible / safe to override the built-in trace labels? https://github.com/googleapis/cloud-trace-nodejs/blob/12a2f8432acfc331b711d8916a1a30c471630d88/src/trace-labels.ts

**Comment by kintel** [comment]
Public docs for using OpenTelemetry with GCP is here: https://cloud.google.com/trace/docs/setup/nodejs-ot
Re. OpenTelemetry: I don't think there are any particular concerns regarding which compute product you use; OpenTelemetry is designed to be as cloud-neutral as possible and that should extend to product-neutral (as long as your GKE components can egress to the Cloud Trace APIs).

**Comment by kintel** [comment]
I wouldn't modify the root span in this case, but rather create a new span for the GraphQL job. This would also allow you to see a separate latency breakdown for the GraphQL request vs. the HTTP request.
I think smth. like this (modulo async execution stuff):
```
  const span = tracer.createChildSpan({name: mySpanName});
  span.addLabel(...);
  // handle gql request
  span.addLabel(...); // For status codes etc.
  span.endSpan();
```

And yes, there is some async-hooks magic that should keep track of the span context per request, as mentioned in the [README](https://github.com/googleapis/cloud-trace-nodejs#how-does-automatic-tracing-work).

**Comment by richardscarrott** [comment]
@kintel Thanks for the help, the child span works well and at least allows us to identify which operation is taking place in the /graphql calls, even if the main trace list is still just /graphql everywhere.

I ended up creating a very simple Apollo Server extension (I think in newer Apollo Server versions they're called 'plugins' and the API may have changed so mileage may vary):

```js
import { get as getTracer } from '@google-cloud/trace-agent';
import { Span } from '@google-cloud/trace-agent/build/src/plugin-types';
import { GraphQLExtension, GraphQLResponse, Request } from 'graphql-extensions';
import { DocumentNode } from 'graphql';

// Types are broken in graphql-extensions so having to redefine them here and assert
interface RequestDidStartObj<GraphQLContext> {
  request: Pick<Request, 'url' | 'method' | 'headers'>;
  queryString?: string;
  parsedQuery?: DocumentNode;
  operationName?: string;
  variables?: { [key: string]: any };
  persistedQueryHit?: boolean;
  persistedQueryRegister?: boolean;
  context: GraphQLContext;
}

interface WillSendResponseObj<GraphQLContext> {
  readonly context: GraphQLContext;
  readonly graphqlResponse: GraphQLResponse;
}

class ApolloGCloudTraceExtension<
  GraphQLContext extends { logger?: Logger }
> extends GraphQLExtension<GraphQLContext> {
  private span: Span;

  constructor() {
    super();
    this.span = getTracer().createChildSpan({ name: 'gql' });
  }

  requestDidStart(obj: any) {
    const { operationName } = obj as RequestDidStartObj<GraphQLContext>;
    this.span.addLabel('operationName', operationName);
  }

  willSendResponse(obj: any) {
    this.span.endSpan();
  }
}

export default ApolloGCloudTraceExtension;
```

I'm sure there's a lot of other information that could be added, e.g. spans for specific gql fields and errors but the above is prob a good starting point for anybody else trying to identify which operation is being performed under /graphql calls.

**Comment by kintel** [comment]
Happy I could be of help, and thanks for posting your solution!
