### ISSUE TITLE
Allow conditionally disabling propagation injection.

### ISSUE THREAD

**Issue by pedrolcn** [googleapis/cloud-trace-nodejs#1326]
**Is your feature request related to a problem? Please describe.**
cloud-trace by default injects trace-propagation headers on all outgoing HTTP requests, this has caused problems with external services which reject requests containing unexpected headers.

 **Describe the solution you'd like**
It should be possible to pass in the configurations object a function (with a signature somwhat like `(options: http.RequestOptions) => boolean`) which should be called at runtime to decide if the propagation headers should be injected.

 **Describe alternatives you've considered**
A less flexible alternative although probably simpler to implement would be to allow passing in the configurations a block-list of domains for which propagation headers should NOT be injected, or maybe an allow-list of domains for which the propagation traces SHOULD be injected

 **Additional context**
The solution currently employed to circumvent this problem is to not inject propagation headers at all, which solves the problem but prevents us from propagating traces on RPCs to internal services.

**Comment by aabmass** [comment]
✋ I can take ownership of this issue but also not sure when I'll get around to a fix. If anyone would like to submit a PR, please drop a comment!

**Comment by aabmass** [comment]
@pedrolcn I'm closing this issue for now. If it's still needed, please reply.

Happy to accept PRs of course :)
