### ISSUE TITLE
Support for WS?

### ISSUE THREAD

**Issue by lucaele** [googleapis/cloud-trace-nodejs#1384]
Hi all,
are there any support for [WS](https://www.npmjs.com/package/ws)?

I'm looking for something that trace time from request to response.

Thanks

**Comment by aabmass** [comment]
Hi @lucaele. It looks like we don't have any instrumentation for this library or web sockets in general.

We don't have capacity to work on any new instrumentations to this agent right now. I'd recommend taking a look at OpenTelemetry which supports exporting to Cloud Trace. From reading https://github.com/open-telemetry/opentelemetry-js-contrib/issues/12, it looks like there is an unofficial instrumentation for `ws` library.
