### ISSUE TITLE
Provided module cannot be loaded

### ISSUE THREAD

**Issue by dschroe93** [googleapis/cloud-trace-nodejs#1393]
When using this lib in my cloud function on nodejs14 it is producing the following issue:

```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module '/src/plugins/plugin-http.js'
...
```

Any help is appreciated.

**Comment by punya** [comment]
I'm closing this issue out as stale, but please feel free to reopen, especially if you're able to provide some concrete repro steps (e.g. your package.json, how you invoked esbuild, etc.).
