### ISSUE TITLE
typescript es6 import, TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by davidbielik** [googleapis/cloud-trace-nodejs#1398]
#### Environment details

  - OS: Mac OS
  - Node.js version: 14.15.4
  - npm version: 7.21.1
  - `@google-cloud/trace-agent` version: 5.1.5

#### Steps to reproduce

  1. `import TraceAgent from '@google-cloud/trace-agent'`
  2. Run `TraceAgent.start();`
  3. Observe the error `TypeError: Cannot read property 'start' of undefined`

To fix this, I needed to instead `import * as TraceAgent`

Suggestions/Questions:

1. Can this be added to the readme, to help with future integrators using es6/typescript imports?
2. I wonder why this wasn't caught by typescript? is there something wrong with the typing provided?

**Comment by dnoe** [comment]
I'm part of the team at Google that maintains the Trace backend and we also own this repository. I'm not a Javascript expert, so I'm flying blind a bit and would definitely appreciate your comments on the PR I created to update the README.md. Let me know if there's a clearer way to say it.

I'm not sure why this wasn't caught by Typescript.

**Comment by davidbielik** [comment]
Thanks @dnoe 

One quick correction to your merged PR:

```
import * as TraceAgent from '@google-cloud/trace-agent';
```

instead of

```
import * from '@google-cloud/trace-agent' as TraceAgent;
```

**Comment by dnoe** [comment]
Thanks for the quick response! I will figure out the proper way to update that README.md so the bot accepts it and we'll get that merged.
