### ISSUE TITLE
Support for version 2.y.z of mysql2

### ISSUE THREAD

**Issue by odanado** [googleapis/cloud-trace-nodejs#1451]
Currently `@google-cloud/trace-agent` only supports 1.y.z mysql2.
https://github.com/googleapis/cloud-trace-nodejs/blob/6f118e9b7fe2194d938bfb3a6e1a8aa763a77b3b/src/plugins/plugin-mysql2.ts#L17

However, the current major version of mysql2 is 2.y.z.
https://www.npmjs.com/package/mysql2

mysql2 includes TypeScript type definitions and other more useful features. Developers will want to use the newer version of mysql2.

**Comment by punya** [comment]
[@opentelemetry/instrumentation-mysql2](https://www.npmjs.com/package/@opentelemetry/instrumentation-mysql2) already supports 2.x. Could you use that instead?
