### ISSUE TITLE
Support `tails` in Hapi

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/cloud-trace-nodejs#382]
As described by @AdriVanHoudt on PR [PR 379](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/379):

"In hapi there is a concept of `tails` where you can still do stuff in your handler after you replied.
In this case you end the span when you call `reply`. I have some routes where I do some queries after replying for performance reasons and it would be great if those queries would also end up in the trace of that request.
Would it be possible to integrate this? You have access to the full request object on that event and it is fired only once per request.
See https://github.com/hapijs/hapi/blob/master/API.md#server-events and https://github.com/hapijs/hapi/blob/master/API.md#requesttailname for more info.
And https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large for a nice overview of how the hapi lifecycle works"

**Comment by AdriVanHoudt** [comment]
Thanks, do you have any initial comments on it? Do you think the proposed change would be ok?

**Comment by matthewloring** [comment]
At first glance, this looks like a good addition but we will want to make sure it is clear in generated spans when a response is sent to the user. Currently, the trace service/UI require that all child spans end before the root span associated with the request. We could make this work for `tails` by introducing a new root span which tracks the time from receiving a request to finishing all associated `tails` with a child span for tracking time between receiving a request and sending a response and a separate child span tracking time spent in the `tails`.

At the moment, we are working to port our existing instrumentation to the new plugin api that you've seen in recent pull requests. For now we are focused on getting the new plugins up to feature parity with the old instrumentations. Once we're finished porting these instrumentations, we can switch back to adding support for new features such as this.

**Comment by kjin** [comment]
This seems blocked by #794
