### ISSUE TITLE
Docs: Better documentation for available configuration options

### ISSUE THREAD

**Issue by jmdobry** [googleapis/cloud-trace-nodejs#523]
While directing users to the library's source code for available configuration options will arguably give them the source of truth, it is quite a jarring experience when users on https://cloud.google.com/trace/docs/setup/nodejs are redirected to a `.js` file on GitHub.

Can we please add a table of available configuration options to the README? 

OR

Can we please get some JSDoc reference docs (that include the available configuration options) published for this library?

Thanks

**Comment by ofrobots** [comment]
Acknowledged. I think handling with with jsdoc reference docs would be a better option.

**Comment by ofrobots** [comment]
Given that this needs to be solved generally across all repos, I am going to move this over to GoogleCloudPlatform/google-cloud-node#2853 and close this issue out.

**Comment by JustinBeckwith** [comment]
It looks like this isn't listed in the available modules over here:
https://github.com/googleapis/google-cloud-node

We need to add a `.repo-metadata` file so this gets picked up and ref docs are published.
