### ISSUE TITLE
`async_hooks`-based tracing doesn't work in cluster

### ISSUE THREAD

**Issue by kjin** [googleapis/cloud-trace-nodejs#659]
```js
const traceAgent = require('.').start({
  samplingRate: 0,
  logLevel: 4
});

const cluster = require('cluster');
const express = require('express');

if (cluster.isMaster) {
  cluster.fork();
} else {
  const app = express();
  app.get('/', (req, res) => {
    res.send('hello!');
  });
  app.listen(8080);
}
```

Multiple `curl localhost:8080` commands lead to the following warning messsages after the first request:

```
WARN:@google-cloud/trace-agent: express: Cannot create nested root spans.
```

This is not observed when the app is run in a single process, and is probably as a result of how forked instances have different behavior when listening on a port.

**Comment by ofrobots** [comment]
@kjin do suspect an issue in cluster, in async-hooks or in this library? (Can you start adding triage labels to issues to help make issue status clearer?)

**Comment by kjin** [comment]
The issue is in Node core; async_hooks doesn't properly wrap incoming HTTP requests in a cluster worker as far as I can tell.

**Comment by ofrobots** [comment]
This is a tracking issue which tracks a bugfix needed in Node. I'm removing the 'bug' label. Once the bug is fixed upstream, we will need to enable tests here.

**Comment by kjin** [comment]
So as it turns out, this isn't a bug at all. See #907
