### ISSUE TITLE
commitlint bot setup but lacking permission

### ISSUE THREAD

**Issue by paulirish** [googleapis/cloud-trace-nodejs#667]
my [commitlintbot project](https://github.com/paulirish/commitlintbot) is set up for this repo.  i think @ofrobots added the webhook to the settings?

however it can't post to a PR's status API because the bot [doesn't have permission](https://github.com/paulirish/commitlintbot#installation).

screenshot from my server logs:
![image](https://user-images.githubusercontent.com/39191/35941859-98ae3ea4-0c08-11e8-80d2-e16d1aa85011.png)

i believe a `GoogleCloudPlatform` org owner will have to grant permission here: https://github.com/settings/connections/applications/e3737bbd21bc66fb0a18

**Comment by ofrobots** [comment]
I'm gonna close this for now.
