### ISSUE TITLE
Plugin request: React

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/cloud-trace-nodejs#754]
Automatic span creation for React components would be very useful in filling in trace gaps for server side rendered applications. There are half a dozen or so well-defined lifecycle methods that could be patched, but in particular, automatically creating spans for the render phase of components would be really helpful.

Some prior art with Zipkin and open tracing is here, but it focuses more on the data requests: https://github.com/react-tracing/react-tracing.

**Comment by kjin** [comment]
Hi @majelbstoat -- I'm not sure if I will have the bandwidth to look at this at least until next month. In the meantime, is there a reference you could point me to for the well-defined lifecycle methods? (I'm not super familiar with React.)

**Comment by majelbstoat** [comment]
Sure thing :) I appreciate the interest, and it's definitely a nice to have. 

Here's a couple of cheatsheets:

http://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/
https://devhints.io/react#lifecycle

And a more in-depth discussion of React components:

https://reactjs.org/docs/react-component.html#componentwillmount

**Comment by kjin** [comment]
Hi @majelbstoat -- I don't think we'll have bandwidth to work on this at all, so I'm going to close this for now. Sorry about that!
