### ISSUE TITLE
Running cloud trace with webpack

### ISSUE THREAD

**Issue by smousa** [googleapis/cloud-trace-nodejs#774]
When I try to start my nodejs service with trace, I see the following error:
```ERROR:@google-cloud/trace-agent: TraceAgent#start: Tracing might not work as the following modules were loaded before the trace agent was initialized: [...]```
and it lists every package dependency in my package.json.

I placed the declaration at the top of index.js:
```require('@google-cloud/trace-agent').start({projectId: 'projectId'})```

Which is where my webpack config js points to:
```
 module.exports = merge(baseWebpackConfig, {
    mode: "development",
    entry: ['webpack/hot/poll?500', './server/index'],
    ....
})
```

Do you know if I am doing something wrong?

**Comment by kjin** [comment]
We currently do not support webpack, since we assume that required modules reside in `node_modules`. I will look into whether we can support this -- but I'm not sure if it's possible.

**Comment by ofrobots** [comment]
@smousa can you include some details on your motivation to use webpack on a server side project? As @kjin said, this is a use-case we have not considered up till now. We would like to understand why/how this is being used to figure what solutions might be possible.

**Comment by smousa** [comment]
Thanks for the reply.  What I have been using webpack was primarily for hot module reloading.  But I think I found a workaround for my immediate issue, which is to initialize tracing in a separate file, like trace.js, require the index and have webpack load trace.js first:

trace.js:
```
require('@google-cloud/trace-agent').start({samplingRate:0})                                                                                                                                                       
require('./index')
```

webpack.*.conf.js
```
module.exports = merge(baseWebpackConfig, {                                     
    mode: "development",                                                        
    entry: ['webpack/hot/poll?500', './server/trace'],                          
    watch: true,                                                                
    externals: [nodeExternals({whitelist:['webpack/hot/poll?500']})],
    ....
```

**Comment by soldair** [comment]
We've done some tests and found that we cannot not support webpack or bundlers at all at this point. 
They "require" files in a way that we cannot instrument them.

**Comment by mrdulin** [comment]
I think it's possible not webpack issue. It's that you didn't import/require the trace agent before other modules.

**Comment by mrdulin** [comment]
@soldair 

It seems trace agent really doesn't support webpack. I have tested it. Here is the repo:
https://github.com/mrdulin/nodejs-gcp/tree/master/src/stackdriver/trace/webpacked-server-code

So, if I use `typescript` as my server-side code and I want to use trace agent. I can't use webpack or bundlers to compile my code? The suggestion is to use typescript compiler?

**Comment by kjin** [comment]
Ultimately what is preventing us from working with transpiled code is whether `require` is re-implemented as part of the transpilation. TypeScript outputs `require` statements with no modification to its implementation, while AFAIK webpack will re-define `require` to reference other blocks of code in the same code, which violates our current assumption that it is the `require` that Node provides us.

**Comment by mrdulin** [comment]
@kjin Thanks for explaining. I have to choose TypeScript compiler instead of choosing webpack. 

And I want to know do you have any plans for supporting webpack? Or, it's an impossible feature?

**Comment by kjin** [comment]
I would not expect TypeScript and webpack are not mutually exclusive, as they have fairly different purposes. That being said, unfortunately, we have no plans to support webpack, apologies for that!
