### ISSUE TITLE
System tests fail on CI

### ISSUE THREAD

**Issue by fhinkel** [googleapis/cloud-trace-nodejs#863]
Trying to land a change that IMHO is unrelated to account credentials. Maybe those got broken when [we switched](https://github.com/googleapis/cloud-trace-nodejs/pull/860) to our usual environment variables? 

```
> Running step: decrypt-service-account-credentials
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```

This PR: 
https://github.com/googleapis/cloud-trace-nodejs/pull/858

This CI run: 
https://circleci.com/gh/googleapis/cloud-trace-nodejs/5755?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by fhinkel** [comment]
@kjin  Can you have a look? I don't know who landed the env variable changes, I only see your closed PR. Thanks!

**Comment by kjin** [comment]
Ah, you'll have to rebase on top of #861 after it lands because I already changed the CircleCI decryption env vars (to show that system tests still pass).
