### ISSUE TITLE
System tests don't run locally

### ISSUE THREAD

**Issue by fhinkel** [googleapis/cloud-trace-nodejs#865]
I can't run the `system tests` locally anymore. Can the error message be improved? The `decrypt` script should not run as part of `npm run system-test` in my opinion.

```
(master)$ npm run system-test

> @google-cloud/trace-agent@3.1.1 system-test /usr/local/google/home/franzih/code/gcp/cloud-trace-nodejs
> npm run script decrypt-service-account-credentials run-system-tests


> @google-cloud/trace-agent@3.1.1 script /usr/local/google/home/franzih/code/gcp/cloud-trace-nodejs
> ts-node -P ./scripts/tsconfig.json ./scripts "decrypt-service-account-credentials" "run-system-tests"

> Running step: decrypt-service-account-credentials
> Environment insufficient to decrypt service account credentials
> Running step: run-system-tests
> Not running system tests in PRs
```

**Comment by kjin** [comment]
I made an unnecessary change in #861 that caused this, opened a PR just now to reverse that. (It's that system tests check that the checked-in, decrypted file exists that causes it to get skipped, not the decryption of credentials, which passes through if it fails)
