### ISSUE TITLE
Plugin request: ioredis

### ISSUE THREAD

**Issue by andzdroid** [googleapis/cloud-trace-nodejs#867]
https://github.com/luin/ioredis

ioredis is a popular redis client, especially since it supports redis sentinel and redis cluster which the node_redis client does not. It's marked as the one other 'recommended client' listed on the redis website: https://redis.io/clients#nodejs

**Comment by ofrobots** [comment]
Previously: https://github.com/googleapis/cloud-trace-nodejs/issues/515.

@andzdroid would you be willing to contribute a plugin? It is not presently high on our priority list, but we will can take a look if you have a PR.

**Comment by ofrobots** [comment]
Given that this feature request (previously #515) hasn't gotten done in the past 2 years, I am going to go ahead and close this out. If anyone wants to contribute a PR that would still be 👍.

**Comment by AdriVanHoudt** [comment]
What are the criteria for certain plugins to be added?

**Comment by ofrobots** [comment]
Hi @AdriVanHoudt. In the past year we were not able to to prioritize this high enough to be able to work on it ourselves. External contributions have been welcome on this, but that didn't materialize either. It is not clear if there is any benefit of keeping the issue open.

Criteria for external PRs for plugins would be something along the lines of:
* Complexity and maintainability. I am not sure how different the `ioredis` plugin would be from `redis` and whether it would be significantly more complex to test and/or maintain. I expect not.
* Substantial use. The target of the plugin (`ioredis`) seems to have have enough downloads on npm to mean that there are a lot users.

Note that a PR to this repo is not necessary for implementing your own plugin. You can simply use/publish an external module and pass the plugin as part of the config to the agent: https://github.com/googleapis/cloud-trace-nodejs#tracing-additional-modules.

**Comment by AdriVanHoudt** [comment]
Ah yeah I totally get why you closed this issue. I was more wondering what the criteria were for the Google team to add plugins. I wish I had actual time to work in this :P

**Comment by klon** [comment]
As node-redis is looking more and more like abandonware (https://github.com/NodeRedis/node-redis/issues/1566) and ioredis seems like the active client project can we get this prioritized? Lack of trace plugin is the only reason we are not moving to ioredis right now.
