### ISSUE TITLE
gRPC client methods are not patched correctly when loaded with @grpc/proto-loader

### ISSUE THREAD

**Issue by jordanworner** [googleapis/cloud-trace-nodejs#873]
When a proto file is loaded with [@grpc/proto-loaded](https://github.com/grpc/grpc-node/blob/master/packages/grpc-protobufjs/src/index.ts#L100) the method names are UpperCamelCase and a property called originalName is added to the method definition that has the lowerCamelCase name.

The [client constructor in the grpc module](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L848) creates a method alias using the originalName.

The problem is the alias is created before the methods are patched, so you can use both to make gRPC calls but only the UpperCamelCase method is traced.

```javascript
import { loadSync } from "@grpc/proto-loader";
import grpc from "grpc";

const credentials = grpc.credentials.createInsecure();

const packageDefinition = loadSync("myservice.proto");
const descriptor = grpc.loadPackageDefinition(packageDefinition);
const client = new descriptor.mypackage.ApiTokenService("0.0.0.0:50051", credentials);

console.log(client.MyMethod);
console.log(client.myMethod);
```

Only client.MyMethod uses clientMethodTrace.

**Comment by kjin** [comment]
Thanks for reporting this! I'm working on getting a fix in now.
