### ISSUE TITLE
configration blocking error

### ISSUE THREAD

**Issue by dlinah** [googleapis/cloud-trace-nodejs#877]
Hi ,
I ran into this problem when i first include the library in my project ,
the `keyFilename` field in configuration object passed to `start` function ,
 when its value is wrong and not found ,it throw an error and closes the application , that is maybe ok ,but the problem is that  the error is also a runtime error .
Please consider to catch the error and give a warning instead.

**Comment by kjin** [comment]
Hi @dlinah -- can you give us a repro case as well as the Node version/agent version you are running? When I run the following, it doesn't seem to bring the process down:

```js
const trace = require('..').start({ keyFilename: 'non-existent', bufferSize: 1 });
trace.runInRootSpan({ name:'my-root' }, span => span.endSpan());
// keep process alive
setInterval(() => {}, 100);
```

**Comment by kjin** [comment]
Hi @dlinah -- we'll be closing this for now. Please feel free to add a comment if you would like us to re-open this issue.
