### ISSUE TITLE
What to do with/about phantom child spans?

### ISSUE THREAD

**Issue by AdriVanHoudt** [googleapis/cloud-trace-nodejs#881]
I'm seeing a lot of these and while these 3 reference /messages I don't think they are directly related though
```
0|api      | @google-cloud/trace-agent ERROR TraceApi#createChildSpan: [mysql@2.16.0:lib/Connection.js] Creating phantom child span [mysql-query] because root span [/messages] was already closed.
0|api      | @google-cloud/trace-agent ERROR TraceApi#createChildSpan: [http@8.12.0:http] Creating phantom child span [metadata.google.internal] because root span [/messages] was already closed.
0|api      | @google-cloud/trace-agent ERROR TraceApi#createChildSpan: [grpc@1.15.1:src/client.js] Creating phantom child span [grpc:/google.logging.v2.LoggingServiceV2/WriteLogEntries] because root span [/messages] was already closed.
```

This might be related to https://github.com/googleapis/cloud-trace-nodejs/issues/382 and thus also to https://github.com/googleapis/cloud-trace-nodejs/issues/794
but wanted to be sure.
That endpoint does make use of tails atm.
The logging thing happens through @google-cloud/logging@1.2.0 but I can probably update that if that helps with anything :D
If there isn't anything I can do for now until the referenced issues are solved, would there be a way to turn these messages of since they are massively spammy atm

**Comment by kjin** [comment]
I've fixed the part related to log levels in #880, though with regards to tail latencies -- I am still working on enabling child spans as tail latencies (as tracked in #794). Thanks for bringing this to our attention.

**Comment by AdriVanHoudt** [comment]
The log level change will probably help 👌 (which was the main issue, I could see y'all working on the tail thing which is stellar ofc ✨ )
If the core of this issue is tracked with #794 you can close this issue ✅

**Comment by kjin** [comment]
Ok, thanks. I'll go ahead and close this issue
