### ISSUE TITLE
Sampling rate too high

### ISSUE THREAD

**Issue by andzdroid** [googleapis/cloud-trace-nodejs#894]
The sampling rate is limited to minimum 1 per second, but this is still too high.

I would like to be able to specify for example 1 per 10 seconds, or even just a percentage like 0.1%.

**Comment by kjin** [comment]
Hi @andzdroid -- we've fixed this in 3.3.0. Please let us know if there are additional issues that need to be addressed!

**Comment by andzdroid** [comment]
Thanks!
