### ISSUE TITLE
Unclear description of the samplingRate configuration

### ISSUE THREAD

**Issue by rueian** [googleapis/cloud-trace-nodejs#904]
There is a snippet in the README.md describing the usage of the `samplingRate`:

```js
require('@google-cloud/trace-agent').start({
  samplingRate: 500, // sample one trace every half-second.
  ignoreUrls: [ /^\/ignore-me#/ ] // ignore the "/ignore-me" endpoint.
});
// ...
```

However, it seems that the description `sample one trace every half-second.` is not correct.
And I think it should be `sample 500 traces every second.`

I found the `samplingRate` is used to create a `Sampler`:
https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/tracing-policy.ts#L84

And the `Sampler` treat it as `samplesPerSecond`:
https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/tracing-policy.ts#L25

**Comment by kjin** [comment]
You're right, the description is wrong. Thanks for the catch!

**Comment by rueian** [comment]
Thank you! The previous comment cost me more than  USD 200 per day on Stackdriver Tracing Billing.

I think this fix will save a lot of people.

**Comment by ofrobots** [comment]
Hi @rueian. We're really sorry about the bug and that it cost you. Would it be possible for you to contact me via email with your project id? My email address is ofrobots@google.com.

**Comment by rueian** [comment]
@ofrobots 

Sure, I will contact you via ruian@dcard.cc
