### ISSUE TITLE
Missing package when installing

### ISSUE THREAD

**Issue by vongohren** [googleapis/cloud-trace-nodejs#918]
Error: Cannot find module 'p-map-series'

Iv been getting these errors the last couple of days as I have rebuilt my images
So they fail and break totally.
Not sure to why though. Because the build and the install works.

<img width="1382" alt="screen shot 2018-11-15 at 11 14 01" src="https://user-images.githubusercontent.com/1012055/48546078-a938ad80-e8c7-11e8-9500-a66ed7432f81.png">

**Comment by ofrobots** [comment]
@vongohren Can you check if the module `orbit-db-access-controllers` properly lists `p-map-series` in its dependencies? That is, does your `node_modules` actually have `p-map-series`? That is likely the problem. 

The reason you see 'trace-module-loader' in the stack is that our instrumentation wants to intercept each module to see if it is one of the frameworks we instrument (e.g. express, mysql, etc.). For a load of `p-map-series` we are deferring to the Node.js module loader. The error suggests that `p-map-series` is not present in the `node_modules` directory.

**Comment by vongohren** [comment]
Yeah im walking down that path now, I just found first package dependency to see what is wrong. But I see that its going further down and will target that package about that problem. But I think we stopped using this the other day, so it should not continue to be a problem when that change is getting into the codebase. Thanks for the response

**Comment by ofrobots** [comment]
Thanks. I'm going to close this issue out as I believe it is not an issue in this library. If this incorrect, please add a comment here, and I will re-open.
