### ISSUE TITLE
ignoreMethods configuration option

### ISSUE THREAD

**Issue by b-flightly** [googleapis/cloud-trace-nodejs#919]
With CORS enabled our stackdriver trace UI is getting overwhelmed with OPTIONS requests.  And I think it might not be reporting important requests since I have a sampling rate < # requests / second.

Having an ignoreMethods configuration option similar to ignoreUrls method would solve this.

**Comment by kjin** [comment]
Hi @b-flightly -- this is available in 3.4.0. Thanks again for your contribution!
