### ISSUE TITLE
req.connection.remoteAddress doesn't return real client ip behind proxies

### ISSUE THREAD

**Issue by sh** [googleapis/cloud-trace-nodejs#942]
We're using trace-agent for connect + express in pods behind a loadbalancer, the value of `/http/source/ip` is always the ip of the loadbalancer instead of the real client.

This makes debugging individual issues based on the `/http/source/ip` currently impossible.

Using `req.ip` instead of `req.connection.remoteAddress` for express and koa would respect any `x-forwarded-for` headers and report the real client ip.

API
- https://expressjs.com/en/4x/api.html#req.ip
- https://koajs.com/#request-ip

Docs
- https://expressjs.com/en/4x/api.html#trust.proxy.options.table
- https://koajs.com/#settings

I'd happily contribute a pull request for this :)

**Comment by sh** [comment]
Done, thanks for taking the time to review this :)

**Comment by kjin** [comment]
@sh no problem, thanks for your contribution! Published in 3.5.0 -- let us know if there are any problems!
