### ISSUE TITLE
mysql2 requests aren't being attached to root scope

### ISSUE THREAD

**Issue by watchinharrison** [googleapis/cloud-trace-nodejs#946]
The log is outputting `INFO TraceApi#createChildSpan: [mysql2@1.6.4:lib/connection.js] Creating phantom child span [mysql-query] because there is no root span.`.

My setup is using knex with the client `mysql2`. The query is running in the knex `raw` method.

This is an example app: https://github.com/davidharrisonlb/mysql-tracer-test

**Comment by davidharrisonlb** [comment]
No problem. I spent the evening trying to work it out too. Think it could be knex’s use of bluebird for promises. Will update with anything further I find today.

**Comment by kjin** [comment]
I think I've found the issue -- it seems that the Trace Agent (or anything reliant on `async_hooks`, for that matter) doesn't work for code that `await`s a custom `thenable`, like a Bluebird Promise (see this [minimum repro](https://gist.github.com/kjin/7e3f3883a6bb47b1783ccae56be8e9bf)). 

This is a problem that is only addressable in Node core, I'll scan the issue list shortly and add it if it's not there. In the meantime, it seems like this functions as a workaround:

```
  // explicitly call the first `.then` rather than let it be implicitly be called via the `await` keyword
  const result = await database.raw('SELECT 1').then(_ => _);
```

**Comment by kjin** [comment]
It seems like it is indeed a variant of an existing issue: https://github.com/nodejs/node/issues/22360.

**Comment by kjin** [comment]
Sorry that this has been stalled. I believe this is a fix that must be done and cannot be done in userspace, so unfortunately I can't amend the bluebird PR to address this issue. You can follow the Node bug here: https://github.com/nodejs/node/issues/26064

**Comment by mrdulin** [comment]
I hit this issue. Trace span doesn't include RPC call to the database.

So, the solution when using `knex.raw` is?

**Comment by giuliano-barberi-tf** [comment]
It looks like Bluebird has been removed in the newest release of knex. Does anyone know if this issue is fixed now?

**Comment by jugglingthebits** [comment]
@giuliano-barberi-tf I have tested this today, and it isn't fixed.

**Comment by samcfinan** [comment]
Experiencing a similar issue with Sequelize v5
