### ISSUE TITLE
Context propagation to go GRPC server stopped working after grpc 1.14.1

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/cloud-trace-nodejs#948]
I have a go GRPC server using the latest version of the go opencensus GRPC server handler (example here: https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ocgrpc/example_test.go). I have a NodeJS client that includes the trace agent, version 3.5.0. 

The client correctly patches a grpc-node 1.14.1 request, creating a child span that is extracted from the metadata on the server and linked with the same traceid by the go server. client and server appear as connected spans in Stackdriver Trace.

However, when using grpc-node version 1.14.2, and all subsequently published version of grpc-node, using the same trace agent 3.5.0, the requests are still patched, and a client child span is still created, but the spans created on the server have a different traceid, indicating that it has not propagated successfully. (Both client and server spans appear in Stackdriver Trace, but are disconnected.)

I went and looked at the changelog between grpc-node 1.14.1 and 1.14.2, and it seems pretty innocuous, but I've confirmed this three times, switching between various different versions of the grpc client library. I have confirmed that with a 1.14.1 client request, the parentID context is successfully extracted, but in the 1.14.2 client request, it isn't. I've confirmed that it doesn't work all the way up to grpc-node 1.17.0.

I'm in control of both the client and the server, so I can give you whatever logs are necessary from the GRPC metadata or headers on either end to help narrow it down.

The client request is promisified with Bluebird in both cases and looks basically like:

```ts
const client = new service.UsersClient('go-service', grpc.credentials.createInsecure())
const getUser = promisify<messages.UserResponse, messages.GetUserRequest>(
  client.getUser.bind(client)
)
await getUser(request).timeout(CREDENTIALS_TIMEOUT)
```

GCLOUD_TRACE_NEW_CONTENT=1

(I have other services that Promisify their requests with Bluebird and they are not connected either, even using grpc-node 1.14.1 😐)

**Comment by kjin** [comment]
That is definitely strange. I'm working on trying to repro this now, will let you know if I need those logs. Thanks for reporting this!

**Comment by kjin** [comment]
I tried repro-ing it by standing up a Node gRPC client and Go gRPC server (based on the helloworld example). It seems like regardless of the Node gRPC version I am seeing the `grpc-trace-bin` header on the Go side, which is the header used to propagate context. This is even if I use Bluebird to promisify the client.

Would you be able to show that the `grpc-trace-bin` headers do not show up on the Go side? Thanks!

**Comment by majelbstoat** [comment]
Oh, sorry, I wasn’t especially clear. The trace bin headers do actually arrive, but the data is still not extracted. I had assumed something had changed in that format. I’ll see if I can decode/extract them to spot the difference.

**Comment by kjin** [comment]
> I had assumed something had changed in that format.

Based on what you said I had assumed that as well, but looking at packet values, at least, there seemed to be no difference. Let me also look into decoding the raw payload values to verify that.

**Comment by ofrobots** [comment]
@majelbstoat Can you look into the headers you are actually receiving. From our side it seems that things should be working okay.

**Comment by ofrobots** [comment]
I'm going to close this due to lack of info. Please add a comment when you have the requested info and we will reopen this.
