### ISSUE TITLE
Feature request: Extract and propagate B3 headers

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/cloud-trace-nodejs#949]
Istio supports distributed tracing on an ingress into a cluster, and between services.

To do this, [it propagates a standard set of B3 headers](https://istio.io/docs/tasks/telemetry/distributed-tracing) (originally defined for Zipkin, I think?) 

```
x-request-id
x-b3-traceid
x-b3-spanid
x-b3-parentspanid
x-b3-sampled
x-b3-flags
x-ot-span-context
```

It would be great if the server side portions of this tracer recognised and propagated the information from that source. [opencensus-node](https://github.com/census-instrumentation/opencensus-node) apparently supports this, though it is itself in very early alpha, and has no GRPC support.

I can share simple istio config that defines this behaviour, if it's helpful.

**Comment by ofrobots** [comment]
Marking this blocked because #950 is blocked.
