### ISSUE TITLE
Support for fastify

### ISSUE THREAD

**Issue by dallerup** [googleapis/cloud-trace-nodejs#977]
I would love to see support for https://www.fastify.io/

**Comment by ofrobots** [comment]
Hi @dallerup! We are in the process of converging this code-base with the [OpenCensus project](https://github.com/census-instrumentation/opencensus-node). At the same time, at this point, we are not sure if fastify has enough usage & demand to be high in our priority list. We will keep an eye on it though. If you are feeling motivated, maybe you can attempt to write a plugin by following our [guide](https://github.com/googleapis/cloud-trace-nodejs/blob/master/doc/plugin-guide.md)?

I'm going to close this issue. Do add a comment if you think this is incorrect.
