### ISSUE TITLE
Tracer periodically forgets configuration and traces every request (badly)

### ISSUE THREAD

**Issue by AaronFriel** [googleapis/cloud-trace-nodejs#994]
Periodically tracing stops working in a weird way that results in *every message* being traced, disregarding the sampling rate *and* the top level root span.

# What I expect to happen

Tracing is configured as so:

```ts
const TRACE_HEADER_BEHAVIOR = process.env.TRACE_HEADER_BEHAVIOR;
let contextHeaderBehavior: 'default' | 'require' = 'default';
let samplingRate: number = 1/60;
if (TRACE_HEADER_BEHAVIOR === 'require') {
  contextHeaderBehavior = TRACE_HEADER_BEHAVIOR;
  samplingRate = 0;
}

export const tracer = traceAgent.start({
  contextHeaderBehavior,
  enabled: process.env.TRACING === 'enabled',
  keyFilename: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  logLevel: 0,
  projectId: process.env.TRACING_PROJECT,
  samplingRate,
});
```

We should expect that we will see one trace per minute, and we do when it is functioning normally. A service is configured to send a heartbeat once per second to a queue service, it runs in a root span called `heartbeat`.

```ts
export async function runHeartbeat(
  parentLogger: Logger,
  dispatcherUri: string,
  rateHz: number,
) {
  const chance = new Chance();

  const durationMs = 1000 / rateHz;

  return pForever(
    async i =>
      tracer.runInRootSpan({ name: 'heartbeat' }, async rootSpan => {
        const logger = traceLogger(parentLogger);

        const message: Payload = {
          payload: JSON.stringify({
            hops: 0,
            i,
            origin: `heartbeat-${os.hostname}-${i}`,
            [chance.string()]: chance.string(),
          }),
        };

        const uri = `${dispatcherUri}`;

        try {
          await postHeartbeat(logger, uri, message);
        } catch (err) {
          logger.error(
            { message, err, dispatcherUri },
            'Error posting message to Dispatcher',
          );
        } finally {
          rootSpan.endSpan();
        }

        await sleep(durationMs);

        return i + 1;
      }),
    1,
  );
}

async function postHeartbeat(
  parentLogger: Logger,
  uri: string,
  message: Payload,
) {
  const logger = traceLogger(parentLogger);
  logger.trace({ message }, 'Posting heartbeat');

  const response = await got.post(uri, {
    body: JSON.stringify(message),
    headers: {
      'Content-Type': 'application/json',
    },
    timeout: 30_000,
  });

  // SAFETY: ! allowed because we are using a POST and not a st1ream
  const statusCode = response.statusCode!;
  const body = response.body;

  if (statusCode < 200 || statusCode >= 300) {
    logger.error({ body, statusCode }, 'Invalid status code');
  }

  return;
}
```

This is what a normal set of traces look like in Stackdriver Trace:

![image](https://user-images.githubusercontent.com/788800/55675120-c1a76580-5872-11e9-9594-fa3c6754a553.png)

We see the root span, we see traces about once per minute (obeying the sampling rate of 1/60), and I can dig into the contents of the child spans, and there are log messages associated with the spans.

# What happens when it breaks

Instead of observing the root span and all child spans across multiple services, I instead see the first HTTP call, a `POST` to `/dispatcher/ping-pong`. And instead of being traced once a minute, I see traces for **every `POST` once a second**. This is extremely strange! It's like the trace service is disregarding my root span entirely, and the sampling rate is being set to 0!

![image](https://user-images.githubusercontent.com/788800/55675106-72f9cb80-5872-11e9-903b-4a012aefebf9.png)

And do you see that `readiness` trace in the screenshot? That's supposed to be filtered out! It's a Kubernetes readiness probe. The server that emitted that has `TRACE_HEADER_BEHAVIOR=require`, so it shouldn't be possible for it to appear! Here's a search for just that path filtered over the last four hours:

![image](https://user-images.githubusercontent.com/788800/55675141-32e71880-5873-11e9-9a63-df7b7acb5e40.png)

**Comment by AaronFriel** [comment]
Oh, this might also be helpful, here's the config for the dispatcher service:

```ts
// tslint:disable: no-submodule-imports
import * as traceAgent from '@google-cloud/trace-agent';

export type Tracer = traceAgent.PluginTypes.Tracer;

export const tracer = traceAgent.start({
  contextHeaderBehavior: 'require',
  enabled: process.env.TRACING === 'enabled',
  keyFilename: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  logLevel: 2,
  projectId: process.env.TRACING_PROJECT,
  samplingRate: 0,
});
```

Note that both `contextHeaderBehavior` is fixed to `'require'`, and `samplingRate: 0`. Is this an improper configuration? I would like all requests to be sampled, but only if they were produced from an incoming traced request.

**Comment by AaronFriel** [comment]
@bcoe would it be possible to chat with someone on support about this? We'd like to roll out google cloud trace to production but the volume could be a blocker. Having our services go from tracing 1 request/minute to *every single request* at random could incur significant costs.

**Comment by kjin** [comment]
@AaronFriel Apologies, I completely missed notifications on this issue. I'm looking into it now.

**Comment by kjin** [comment]
The Trace Agent's config is static, and our sampling rate logic is fairly straightforward so I'm not sure what would cause periodic moments where traces don't get sampled out. Can you provide more details on how often it happens and roughly how long the bursts last (and just for sanity, verify that the flood of requests is coming from the heartbeat client)?

> Note that both `contextHeaderBehavior` is fixed to `'require'`, and `samplingRate: 0`. Is this an improper configuration?

No, that seems reasonable for a non-public service.

**Comment by AaronFriel** [comment]
I have not been able to reproduce this on a fork, and I suspect the issue was a misconfiguration with `contextHeaderBehavior: default, samplingRate: 0`. This was a mistake, but also an attempt to get a behavior that I will describe below.

I would like a hybrid behavior of `default` and `require`. Let's call that mode `end-to-end`:

1. If a request comes in with a trace header, always trace it (equivalent to setting the trace policy to Always or, in `trace-api.ts` or setting `locallyAllowed = true` in `trace-api.ts`.)

2. If a request does not come in with a trace header, behave exactly like `default`.

This would mean that:

1. Requests that come in with a trace header are **always** traced, even if they hit an ignored URL or the sampling rate would forbid it.

2. Running `runInRootSpan` / untraced requests behave according to `default` rules, applying the trace policy.

For all externally facing APIs, this ensures that a trace originating outside is **always** end to end, including all RPCs from all intermediary services.

For internally facing APIs, we will also get a random sampling of partial traces. If the end-to-end trace is a directed acyclic graph or more precisely a tree (it is), then this would amount to also collecting random subtrees of the graph.

This would be very useful for us, because it would allow us to capture not just end-to-end latency and request errors, but also partial graph latencies.

**Comment by kjin** [comment]
@AaronFriel Thanks for coming back to this. I'd be glad to implement `end-to-end` as an option, but I'm wondering what your thoughts would be on, in lieu of this, a new feature to specify your own `TracePolicy` implementation in the config (which would just boil down to [providing a `shouldTrace` method](https://github.com/googleapis/cloud-trace-nodejs/blob/v3.6.1/src/tracing-policy.ts)). This `shouldTrace` currently does not get trace headers as an argument, but it would as part of this change. This way you (and others) would have more freedom to choose how requests are traced rather than go through the issue/PR process.

**Comment by AaronFriel** [comment]
@kjin That would be fine and it would fix a related bug (?) I found!

I would like the modified `shouldTrace` to receive in the arguments object the existing values: `timestamp`, `url`, `method`, as well `options` (to receive the values from `RootSpanOptions`) and `parsedContext` (no need to run `util.parseContextFromHeader` twice).
