### ISSUE TITLE
Keep getting crashes with message "Tracing might not work as the following modules were loaded before the trace agent" when I am using trace agent with PM2.

### ISSUE THREAD

**Issue by SudhagarS** [googleapis/cloud-trace-nodejs#995]
`@google-cloud/trace-agent ERROR StackdriverTracer#start: Tracing might not work as the following modules were loaded before the trace agent was initialized: [@pm2/io, ansi-styles, async, chalk, color-convert, color-name, date-fns, debug, escape-string-regexp, event-loop-inspector, eventemitter2, fclone, has-flag, lodash, ms, pm2, semver, shimmer, supports-color, tslib]`

I don't mind this coming as a warning. But process restarts because of this issue. Is that the expected behaviour?

**Comment by ofrobots** [comment]
This is supposed to be a warning message only, and we do not stop the process. Here's the code:
https://github.com/googleapis/cloud-trace-nodejs/blob/5c01e9e19643f40f38f445a775e988a45779da36/src/tracing.ts#L86-L91

I don't see a reason for the process to restart as a result. Maybe something else is restarting the process?

**Comment by ofrobots** [comment]
The above function is called from here: https://github.com/googleapis/cloud-trace-nodejs/blob/199cb42804899fa8d76d6cdcab283b1543f74267/src/index.ts#L145-L147

We continue and return a valid `traceAgent` regardless.

**Comment by vmarchaud** [comment]
FYI, those modules are required before the tracing agent because pm2 launch a wrapper around any `.js` app there: https://github.com/Unitech/pm2/blob/master/lib/ProcessContainerFork.js#L7

**Comment by SudhagarS** [comment]
@vmarchaud this is what I get

2019-04-09T15:10:38: PM2 log: Stopping app:backend id:0
2019-04-09T15:10:38: PM2 log: App name:backend id:0 disconnected
2019-04-09T15:10:38: PM2 log: App [backend:0] exited with code [0] via signal [SIGINT]
2019-04-09T15:10:38: PM2 log: pid=19518 msg=process killed
2019-04-09T15:10:38: PM2 log: App [backend:0] starting in -cluster mode-

**Comment by kjin** [comment]
@SudhagarS also, do you experience this when the Trace Agent is not enabled?

**Comment by kjin** [comment]
Hi @SudhagarS, I'm closing this issue for housekeeping purposes, please let us know if you have any other info and I can re-open the issue.
